{% set name = "django-pandas" %}
{% set version = "0.6.6" %}
{% set sha256 = "514d701452e85fed8f8efa28bd8a650a1c3e995f0cd550884df174a0ca90d71f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - pandas >=0.14.1
    - python >=3.6
    - six >=1.15.0
  run_constrained:
    - django >=1.4.5

test:
  imports:
    - django_pandas
    - django_pandas.tests
  commands:
    - pip check
  requires:
    - pip
    - django >=1.4.5
    
about:
  home: https://github.com/chrisdev/django-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Tools for working with pandas in your Django projects'
  description: 
    Tools for working with pandas in your Django projects
  doc_url: https://media.readthedocs.org/pdf/django-pandas/latest/django-pandas.pdf
  dev_url: https://github.com/chrisdev/django-pandas

extra:
  recipe-maintainers:
    - jacksund
    - cshaley
    - sannykr
