{% set name = "django-pandas" %}
{% set version = "0.6.4" %}
{% set sha256 = "a1b5d300112a09625926a5756aa72bbe8918fb95b9c4ec39b3a06f03e0e336f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - django >=1.4.5
    - django-model-utils >=1.4.0
    - pandas >=0.14.1

test:
  imports:
    - django_pandas
  requires:
    - django >=1.4.2
    - pandas 0.20.1
    - coverage >=4.0

about:
  home: https://github.com/chrisdev/django-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for working with pandas in your Django projects
  description: Tools for working with pandas in your Django projects
  doc_url: https://media.readthedocs.org/pdf/django-pandas/latest/django-pandas.pdf
  dev_url: https://github.com/chrisdev/django-pandas

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
